# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\computer_vision\image_processing_gui\image_processing_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 504)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(840, 504))
        MainWindow.setMaximumSize(QtCore.QSize(840, 504))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(660, 20, 171, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pBtn_normal = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pBtn_normal.setObjectName("pBtn_normal")
        self.verticalLayout.addWidget(self.pBtn_normal)
        self.pBtn_gray = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pBtn_gray.setObjectName("pBtn_gray")
        self.verticalLayout.addWidget(self.pBtn_gray)
        self.pBtn_canny = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pBtn_canny.setObjectName("pBtn_canny")
        self.verticalLayout.addWidget(self.pBtn_canny)
        self.pBtn_recognition = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pBtn_recognition.setObjectName("pBtn_recognition")
        self.verticalLayout.addWidget(self.pBtn_recognition)
        self.pBtn_close = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pBtn_close.setObjectName("pBtn_close")
        self.verticalLayout.addWidget(self.pBtn_close)
        self.ImageViewer = QtWidgets.QLabel(self.centralwidget)
        self.ImageViewer.setGeometry(QtCore.QRect(10, 10, 640, 480))
        self.ImageViewer.setFrameShape(QtWidgets.QFrame.Box)
        self.ImageViewer.setText("")
        self.ImageViewer.setObjectName("ImageViewer")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(660, 240, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Computer Vision"))
        self.pBtn_normal.setText(_translate("MainWindow", "Normal"))
        self.pBtn_gray.setText(_translate("MainWindow", "Gray"))
        self.pBtn_canny.setText(_translate("MainWindow", "Canny Edge Dedector"))
        self.pBtn_recognition.setText(_translate("MainWindow", "Object Recognition"))
        self.pBtn_close.setText(_translate("MainWindow", "Kapat"))
        self.label.setText(_translate("MainWindow", "FPS:"))
